### PR TITLE
🔥 Removal of `NotEmptyRange` and `*Bound` types

### LINKED ISSUE #618: 🔥 Deletion of `NotEmptyRange` and `*Bound` types
> [!IMPORTANT]
> This is an **incompatible source and binary change**. See our [versioning strategy](https://github.com/kotools/types/blob/main/documentation/versioning-strategy.md) for more details on when to publish it.

## 📝 Description

Due to an internal compilation error of Kotlin when comparing generic types, we want to remove the following types from our experimental API: `NotEmptyRange`, `Bound`, `InclusiveBound` and `ExclusiveBound`.

## ✅ Checklist

- [x] Remove the `NotEmptyRange` type and dump the Application Binary Interface (ABI).
- [x] Remove the `Bound` type and dump the Application Binary Interface (ABI).
- [x] Remove the `InclusiveBound` type and dump the Application Binary Interface (ABI).
- [x] Remove the `ExclusiveBound` type and dump the Application Binary Interface (ABI).
- [x] Add an entry for this issue in the [unreleased changelog].

[api binaries]: https://github.com/kotools/types/blob/main/CONTRIBUTING.md#checking-the-api-binaries
[unreleased changelog]: https://github.com/kotools/types/blob/main/CHANGELOG.md#unreleased

### PR DESCRIPTION
**Pull request by augustomtt**
> Close #618 

- Due to an internal compilation error of Kotlin when comparing generic types, the following types from the experimental API are being removed `NotEmptyRange`, `Bound`, `InclusiveBound `and `ExclusiveBound`.
- [Unreleased changelog](https://github.com/kotools/types/blob/main/CHANGELOG.md#unreleased) entry was not added and is pending for a future commit.
- Tests that referenced the generic types listed before were also deleted.

### CODE REVIEW

**Comment by LVMVRQUXL** [comment]
Thank you @augustomtt for your contribution! 🙏
I see that all your commits are signed right now. 😉
I will go throw the request and review it very soon. 😁

**Review by LVMVRQUXL — CHANGES_REQUESTED** [review]
@augustomtt Please rebase your `feature/618` branch on the `main` one for avoiding merge commits like 402d4f08ee5c59b583b8bd8a2f2b83da07cfae1a. 🙂

**Comment by augustomtt** [comment]
Sorry!! My mistake! I will fix it now 😬

**Comment by augustomtt** [comment]
So sorry for the mess I made, this are my first commits to open source repositories, it won't happen again!
Could you fix the conflict? It seems related to a simple name-ordering in the changelog, it's up to you who goes first! 😅

**Comment by LVMVRQUXL** [comment]
No problem @augustomtt, I will help you on this! 😁

I'm gonna fix the commit history in a bit using the latest version of the `main` branch on this repository. My changes might force-push your branch. 😉

**Comment by LVMVRQUXL** [comment]
@augustomtt I am also editing your commit messages for better alignment with our conventions. 🧑‍💻

**Comment by LVMVRQUXL** [comment]
I've fixed the commit history @augustomtt and also added an entry in the unreleased changelog. 🙌
Let's review the changes while checks are running. 😉

**Review by LVMVRQUXL — APPROVED** [review]
This request is ready to merge! 🚀
Thank you again @augustomtt for your contribution. 🙏
I wait for the running checks to succeed before merging. ✅

**Comment by augustomtt** [comment]
Awesome!! 🤠

**Comment by LVMVRQUXL** [comment]
@augustomtt This request is successfully merged! 🎉

Feel free to show your support on this project by starring it on GitHub and activating the release notification for being noticed when your changes will be published to the world. 🌐

Also, if you have any feedback or suggestion about Kotools Types, I will be happy to read your thoughts. And as always, feel free to contribute on another issue or discussion. 😁

**Pull request merged**
